### PR TITLE
Add New Colour Scheme

### PR DESCRIPTION
**Pull request by ghost**
Added a new colour scheme, with GREEN_ON_BLACK being its main colour.  
To use it, append `colorScheme 2` to your .breadtextrc.

### CODE REVIEW

**Comment by ostracod** [comment]
Thanks for the contribution, but a couple of things:

- Please modify display.c inside of the src directory instead of creating a new file.
- Please use 4 spaces instead of hard tabs.

**Comment by ostracod** [comment]
Almost there. Please perform `git rm ./display.c` to remove the extra display.c file.

**Comment by ostracod** [comment]
Thanks!

**Comment by ghost** [comment]
No problem, sorry for wasting some time by not knowing how to use git very well.

**Comment by ostracod** [comment]
No problem, learning is good. 😃

**Pull request merged**
